/** Default pricing config — seeded to Firestore `config/pricing` on first read. */

export const DEFAULT_PRICING_CONFIG = {
  currency: "INR",
  currencySymbol: "₹",
  plans: {
    yearly: {
      id: "yearly",
      label: "Glowminds Pro Yearly",
      displayPrice: "₹399",
      period: "/year",
      amountPaise: 39900,
      durationDays: 365,
    },
    monthly: {
      id: "monthly",
      label: "Glowminds Pro Monthly",
      displayPrice: "₹49",
      period: "/month",
      amountPaise: 4900,
      durationDays: 30,
    },
  },
  freeLimits: {
    applications: 5,
    resumes: 3,
    template: "onyx",
  },
  pricing: {
    free: {
      label: "FREE",
      price: "₹0",
      period: "/forever",
      desc: "Perfect for getting started with job hunting.",
      features: [
        "Job search & matching",
        "1 resume template",
        "5 application tracking slots",
        "Profile & portfolio",
        "Daily quiz & streaks",
      ],
    },
    pro: {
      label: "PRO",
      price: "₹399",
      period: "/year",
      desc: "Everything you need to land your dream job.",
      features: [
        "Unlimited resumes & templates",
        "AI Career Coach 24/7",
        "Interview Prep with scoring",
        "Unlimited application tracking",
        "Grammar Checker unlimited",
        "Cover Letter Generator",
        "LinkedIn Optimizer & Cold Email Drafter",
        "Priority job alerts & salary insights",
      ],
    },
  },
  freeFeatures: [
    { text: "Job Search & Browse", included: true },
    { text: "Profile & Portfolio", included: true },
    { text: "3 Resumes (Onyx template)", included: true },
    { text: "5 Application Tracking", included: true },
    { text: "Basic Job Alerts", included: true },
    { text: "AI Career Coach", included: false },
    { text: "Interview Prep AI", included: false },
    { text: "Cover Letter Generator", included: false },
    { text: "All Resume Templates", included: false },
    { text: "Unlimited Tracking", included: false },
    { text: "Salary Insights", included: false },
    { text: "Priority Support", included: false },
  ],
  proFeatures: [
    { text: "Everything in Free", included: true, highlight: false },
    { text: "AI Career Coach (24/7)", included: true, highlight: true },
    { text: "AI Interview Prep", included: true, highlight: true },
    { text: "All 6 Resume Templates", included: true, highlight: false },
    { text: "Cover Letter Generator", included: true, highlight: true },
    { text: "Unlimited Applications", included: true, highlight: false },
    { text: "Unlimited Resumes", included: true, highlight: false },
    { text: "Salary Insights & Analytics", included: true, highlight: false },
    { text: "Skill Gap Analysis", included: true, highlight: true },
    { text: "Real-time Job Alerts", included: true, highlight: false },
    { text: "1-Click Apply", included: true, highlight: false },
    { text: "Priority Support", included: true, highlight: false },
  ],
  pricingComparison: [
    { feature: "Job Search", free: "Basic", pro: "Advanced + AI" },
    { feature: "Resume Builder", free: "3 resumes · Onyx template", pro: "Unlimited · all templates" },
    { feature: "Application Tracker", free: "5 apps", pro: "Unlimited" },
    { feature: "AI Career Coach", free: "—", pro: "24/7 access" },
    { feature: "Interview Prep", free: "—", pro: "AI evaluator" },
    { feature: "Cover Letters", free: "—", pro: "AI generated" },
    { feature: "Salary Insights", free: "—", pro: "Full data" },
    { feature: "Job Alerts", free: "Daily digest", pro: "Real-time" },
    { feature: "Support", free: "Community", pro: "Priority" },
  ],
  pricingFaqs: [
    {
      q: "What does the yearly plan include?",
      a: "The Pro yearly plan gives you unlimited access to every feature — AI Career Coach, Interview Prep, all resume templates, cover letter generator, salary insights, and priority support. One payment, 12 months of full access.",
    },
    {
      q: "Can I cancel anytime?",
      a: "Yes. You can cancel your subscription at any time from your dashboard. You'll continue to have Pro access until the end of your billing period. No questions asked.",
    },
    {
      q: "Is there a free trial?",
      a: "We offer a generous free tier instead of a trial. You can use core features forever — job search, 1 resume, and 5 application tracking slots. Upgrade to Pro when you're ready.",
    },
    {
      q: "How does payment work?",
      a: "We use Razorpay for secure payments. You can pay with UPI, credit/debit card, net banking, or wallets. Your payment information is encrypted end-to-end.",
    },
    {
      q: "Can I use this as a non-student?",
      a: "Absolutely. While Glowminds is optimized for students and fresh graduates, anyone early in their career or looking to switch roles can benefit from our tools.",
    },
  ],
  marketing: {
    proTagline: "Just ₹33/month billed yearly — less than a cup of coffee",
    monthlyEquivalent: "₹33/month",
    heroDescription: "Unlimited access to AI-powered career tools. Built for students, priced for students. Just ₹33/month.",
    billingBlurb: "One payment of ₹399/year — about ₹33/month. Secure checkout via Razorpay (UPI, cards, net banking).",
    termsBillingText:
      "Pro subscriptions are billed annually at ₹399/year. Payments are processed securely through Razorpay. You can cancel your subscription at any time from your dashboard. Cancellations take effect at the end of the current billing period.",
  },
};
