/** Default pricing config — seeded to Firestore `config/pricing` on first read. */

export const DEFAULT_PRICING_CONFIG = {
  currency: "INR",
  currencySymbol: "₹",
  plans: {
    yearly: {
      id: "yearly",
      label: "Glowminds Pro Yearly",
      displayPrice: "₹599",
      regularPrice: "₹999",
      period: "/year",
      amountPaise: 59900,
      durationDays: 365,
    },
    monthly: {
      id: "monthly",
      label: "Glowminds Pro Monthly",
      displayPrice: "₹99",
      period: "/month",
      amountPaise: 9900,
      durationDays: 30,
    },
  },
  freeLimits: {
    applications: 10,
    resumes: 1,
    aiCredits: 5,
    template: "onyx",
  },
  proLimits: {
    aiCreditsPerMonth: 100,
  },
  creditCosts: {
    careerChat: 1,
    coverLetter: 5,
    interviewSession: 10,
    profileReview: 1,
    grammar: 1,
    paraphrase: 1,
  },
  pricing: {
    free: {
      label: "FREE",
      price: "₹0",
      period: "/forever",
      desc: "Perfect for getting started with job hunting.",
      features: [
        "Job search & matching",
        "1 resume (Onyx template)",
        "10 application tracking slots",
        "5 AI credits to try",
        "Profile & portfolio",
        "Job alerts",
      ],
    },
    pro: {
      label: "PRO",
      price: "₹599",
      regularPrice: "₹999",
      period: "/year",
      desc: "Everything you need to land your dream job.",
      highlights: [
        "ATS Resume Builder",
        "AI Mock Interviews",
        "AI Cover Letters",
        "Smart Job Matching",
        "Application Tracking",
      ],
      features: [
        "100 AI credits/month (fair usage applies)",
        "All 15 resume templates",
        "Unlimited application tracking",
        "AI Mock Interviews (10 credits/session)",
        "AI Cover Letters (5 credits each)",
        "AI Coach Chat (1 credit/message)",
        "Smart job matching & alerts",
        "Salary insights & analytics",
      ],
    },
  },
  freeFeatures: [
    { text: "Job Search & Browse", included: true },
    { text: "Profile & Portfolio", included: true },
    { text: "1 Resume (Onyx template)", included: true },
    { text: "10 Application Tracking", included: true },
    { text: "5 AI Credits", included: true },
    { text: "Job Alerts", included: true },
    { text: "AI Career Coach", included: false },
    { text: "Interview Prep AI", included: false },
    { text: "Cover Letter Generator", included: false },
    { text: "All Resume Templates", included: false },
    { text: "Unlimited Tracking", included: false },
    { text: "Salary Insights", included: false },
    { text: "Priority Support", included: false },
  ],
  proFeatures: [
    { text: "Everything in Free", included: true, highlight: false },
    { text: "100 AI Credits/month", included: true, highlight: true },
    { text: "AI Mock Interviews (10 credits/session)", included: true, highlight: true },
    { text: "AI Cover Letters (5 credits each)", included: true, highlight: true },
    { text: "AI Coach Chat (1 credit/message)", included: true, highlight: true },
    { text: "All 15 Resume Templates", included: true, highlight: false },
    { text: "Unlimited Applications", included: true, highlight: false },
    { text: "Unlimited Resumes", included: true, highlight: false },
    { text: "Salary Insights & Analytics", included: true, highlight: false },
    { text: "Real-time Job Alerts", included: true, highlight: false },
    { text: "Priority Support", included: true, highlight: false },
  ],
  pricingComparison: [
    { feature: "Job Search", freeIncluded: true, proIncluded: true, freeDetail: "Basic", proDetail: "Advanced + AI" },
    { feature: "Resume Builder", freeIncluded: true, proIncluded: true, freeDetail: "1 resume · Onyx", proDetail: "Unlimited · all templates" },
    { feature: "Application Tracker", freeIncluded: true, proIncluded: true, freeDetail: "10 apps", proDetail: "Unlimited" },
    { feature: "AI Credits", freeIncluded: true, proIncluded: true, freeDetail: "5 total", proDetail: "100/month" },
    { feature: "AI Career Coach", freeIncluded: false, proIncluded: true, proDetail: "1 credit/message" },
    { feature: "Interview Prep", freeIncluded: false, proIncluded: true, proDetail: "10 credits/session" },
    { feature: "Cover Letters", freeIncluded: false, proIncluded: true, proDetail: "5 credits each" },
    { feature: "Salary Insights", freeIncluded: false, proIncluded: true },
    { feature: "Job Alerts", freeIncluded: true, proIncluded: true, freeDetail: "Basic", proDetail: "Real-time" },
    { feature: "Support", freeIncluded: true, proIncluded: true, freeDetail: "Community", proDetail: "Priority" },
  ],
  pricingFaqs: [
    {
      q: "Is Glowminds free?",
      a: "Yes. The free plan includes job search, profile, job alerts, 1 resume, 10 application tracking slots, and 5 AI credits to try our tools. No credit card required.",
    },
    {
      q: "Why is Glowminds Pro so affordable?",
      a: "We're in our founding launch phase and priced Pro for students and early-career professionals in India. Founding members lock in ₹599/year (regular ₹999) — less than ₹2/day for AI resumes, interview prep, and job matching.",
    },
    {
      q: "Do AI features have usage limits?",
      a: "Yes. Pro includes 100 AI credits per month. Cover letters cost 5 credits, mock interview sessions cost 10 credits, and AI Coach chat messages cost 1 credit each. A fair usage policy applies to prevent abuse.",
    },
    {
      q: "Can I cancel anytime?",
      a: "Yes. Cancel from your dashboard at any time. You'll keep Pro access until the end of your billing period. No questions asked.",
    },
    {
      q: "Is my resume data secure?",
      a: "Yes. Your resumes and profile data are stored securely. Payments are processed through Razorpay — we never store your card or UPI details.",
    },
    {
      q: "Do I need a credit card for the free plan?",
      a: "No. Sign up and use the free tier forever without entering payment details. Upgrade to Pro only when you're ready.",
    },
    {
      q: "Can working professionals use Glowminds?",
      a: "Absolutely. While Glowminds is optimized for students and fresh graduates, anyone early in their career or switching roles can benefit from our AI tools.",
    },
  ],
  marketing: {
    proTagline: "Only ₹50/month when billed annually — less than ₹2/day",
    monthlyEquivalent: "Only ₹50/month when billed annually",
    dailyEquivalent: "Less than ₹2/day",
    heroDescription:
      "AI-powered resumes, interview prep, and job matching — built for students and early-career professionals. Join as a founding member at our launch price.",
    billingBlurb:
      "Founding member offer: ₹599/year (regular ₹999). Secure checkout via Razorpay (UPI, cards, net banking).",
    termsBillingText:
      "Pro subscriptions are billed at ₹599/year (founding member offer; regular price ₹999/year) or ₹99/month. Payments are processed securely through Razorpay. You can cancel your subscription at any time from your dashboard. Cancellations take effect at the end of the current billing period.",
    proHighlights: [
      "ATS Resume Builder",
      "AI Mock Interviews",
      "AI Cover Letters",
      "Smart Job Matching",
      "Application Tracking",
    ],
    launchOfferText: "Founding Member Offer",
    guaranteeText: "7-day money-back guarantee — try Pro risk-free.",
    socialProof: "Trusted by students from NITs, IIITs, and state universities across India.",
  },
};
