packages:
  - .
  - packages/*

allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  msw: true
  protobufjs: true

patchedDependencies:
  '@react-pdf/textkit@6.3.0': packages/glowminds-resume/patches/@react-pdf__textkit@6.3.0.patch
