/**
 * College / university names for profile education (searchable combobox).
 * Andhra Pradesh regional institutions.
 */
export const INDIAN_COLLEGES = [
  'ACHARYA COLLEGE OF ENGG, BADVEL, KADAPA',
  'Acharya College of Engineering, Badvel',
  'Aditya College of Engineering, Madanapalle',
  'Anantha Lakshmi Institute of Technology & Sciences',
  'ANDHRA ENGINEERING COLLEGE',
  'Annamacharya College of Pharmacy, Rajampet',
  'ANNAMACHARYA INSTITUTE OF TECHNOLOGY AND SCIENCE, CK DINNE, KADAPA',
  'Annamacharya Institute of Technology and Sciences, Chinthakomma Dinne',
  'Annamacharya Institute of Technology & Sciences, (Autonomous) New Boyanapally, Rajampet',
  'Annamacharya Pg College Of Computer Studies',
  'Annamacharya P.G. College of Computer Studies, Rajampet',
  'Annamacharya Institute of Technology & Sciences, Tirupati',
  'Annamacharya Institute of Technology & Sciences, Tirupati',
  'ASHOKA WOMEN ENGINEERING COLLEGE, KURNOOL',
  'AUDISANKARA COLLEGE OF ENGG & TECH, Gudur, Nellore',
  'Audisankara College of Engineering & Technology, Gudur',
  'Audisankara Institute of Technology, Gudur',
  'AUDISANKARA INST. OF TECH, Gudur',
  'Balaji College of Pharmacy, Anantapur',
  'BALAJI COLLEGE OF PHARMACY, ANANTAPUR',
  'Balaji Institute of I.T & Management',
  'BESGIFE, ANGALLU, CHITTOOR',
  'Bharath College of Engineering and Technology for Women',
  'Bharath Educational Society Group of Institutions, (Integrated Campus) Angallu',
  'Bheema Institute of Technology & Sciences, Adoni',
  'Bheemi Reddy Institute of Management Science, Adoni',
  'BIT Institute of Technology, (F3) Hindupur',
  'BIT INSTITUTE OIF TECHNOLOGY, HINDUPUR',
  'Brahmaiah College of Engineering',
  'BRINDAVAN INSTITUTE OF TECHNOLOGY AND SCIENCE, KURNOOL',
  'BRINDAVAN INSTITUTE OF TECHNOLOGY & SCIENCE',
  'Chadalawada Ramanamma Engineering College, Tirupati',
  'Chadalawada Venkata Subbaiah College of Engineering, Tirupathi',
  'CHAITANAYA BHARATHI, PRODDATUR, KADAPA',
  'Chaitanya Bharathi Institute of Technology, Proddatur',
  'CHINARJEEV REDDY INSTITUTE OF ENGINEERING AND TECHNOLOGY, RACHANAPALLI, ANANTAPUR',
  'Chiranjeevi Reddy Institute of Engineering and Technology, Anantapur',
  "Creative Educational Society's College of Pharmacy, Kurnool",
  'CREATIVE EDUCATIONAL SOCIETY COLLEGE OF PHARMACY, KURNOOL.',
  'Danisetty Bala Suresh Institute of Technology, Kavali',
  'Danisetty Bala Suresh Institute of Technology, MADDURUPADU, KAVALI',
  'DR. JYOTHIRMAYI DEGREE COLLEGE (MBA), BEHIND APHB COLONY, RAMAJALA ROAD, ADONI',
  'Dr.K V Subba Reddy College of Engineering for Women, Kurnool',
  'DR K V SUBBA REDDY INSTITUTE OF MANAGEMENT',
  'DR K V SUBBA REDDY INSTITUTE OF MCA',
  'Dr.K.V Subba Reddy Institute of Pharmacy, Kurnool',
  'DR.KV SUBBA REDDY INSTITUTE OF PHARMACY, KURNOOL',
  'Dr.K V Subba Reddy Institute of Technology, Kurnool',
  'GATE INSTITUTE OF TECHNOLOGY, GOOTY',
  'GATES Institute of Technology, Gooty',
  'Geethanjali College of Engineering & Technology, Kurnool',
  'Geethanjali Institute of Science and Technology',
  'GITAMS Business and IT School',
  'Global College of Engineering & Technology',
  'Gokulakrishna College of Engineering, Sullurpet',
  'Gokula Krishna College of Pharmacy, Sullurpet',
  'GOKUL KRISHNA COLLEGE OF ENGINEERING, SULLURPET',
  'GOLBAL COLLEGE OF ENGINEERING AND TECHNOLOLGY, CHINNAMACHUPALLI, KADAPA',
  'Goutami Institute of Technology & Management for Women, Proddatur',
  'GOWTHAMI INSTITUTE OF TECHNOLOGY AND MANGAMENT, PEDDASETTIPALLI, PRODDATUR',
  'G.Pullaiah College of Engineering & Technology, Kurnool',
  'G. Pulla Reddy Engineering College, (Autonomous), Kurnool',
  'JAGANS COLLEGE OF ENGINEERING AND TECHNOLOGY, CHAVATAPALEM, NELLORE',
  "Jagan's College of Engineering & Technology",
  "Jagan's College of Pharmacy, Muthukur",
  'JAGANS COLLEGE OF PHARMACY, NELLORE',
  'JAGANS INSTITUTE OF PHARMACEUTICAL SCIENCE, NELLORE',
  "Jagan's Institute of Pharmaceutical Sciences",
  'JNTUA College of Engineering, Anantapur',
  'JNTUA College of Engineering, Kalikiri',
  'JNTUA COLLEGE OF ENGINEERING, KALIKIRI',
  'JNTUA College of Engineering, Pulivendula',
  'JNTUA - EDUTALKS',
  'JNTUA Oil Technological and Pharmaceutical Research Institute',
  'Kandula Lakshumma College of Engg. for Women',
  'KANDULA OBUL REDDY MEMORIAL COLLEGE OF ENGINEERING, THADIGOTLA, KADAPA',
  'KMM INSTITUTE OF TECHNOLOGY AND SCIENCE, RAMIREDDIPALLE, TIRUPATI',
  'KMM Institute of Technology & Science, Tirupathi',
  'KORM College of Engineering',
  'Krishna Teja Pharmacy College, Tirupati',
  'K.S.R.M. College of Engineering',
  'K.S.R.M. College of Management Studies',
  'Kuppam Engineering College, Chittoor',
  'Madanapalle Institute of Technology & Science, Madanapalle',
  'Madura Sai Institute of IT & Management, Proddatur',
  'Maharshi College Of Pharmacy, Madanapalle',
  'Maharshi College of Pharmacy, Madanapalle',
  'Mekapati Rajamohan Reddy Inst. of Tech & Science, Udayagiri',
  'M.J.R. College of Engineering & Technology, Pulicherla',
  'Mjr Coll. Of Engg. And Technology',
  'MJR INSTITUTE OF BUSINESS MANAGEMENT, DIGUVAPOKULAVARIPALLI (V), PULICHERLA (M)',
  'Mother Theresa Institute of Engineering & Technology, Palamaner',
  'MOTHER THERESA INSTITUTE OF PHARMACEUTICAL EDUCATION AND RESEARCH',
  'Mother Theresa Institute of Pharmaceutical Education ..., KURNOOL.',
  'Narayanadri Institute of Science & Technology, Rajampet',
  'Narayanadri Institute of Science and Technology, RAJAMPET, KADAPA',
  'Narayana Engineering College',
  'Narayana Engineering College-Gudur',
  'NARAYANA ENGINEERING COLLEGE, NELLORE',
  'Narayana Pharmacy College, Chinthareddypalem',
  'N B K R INSTITUTE OF SCIENCE & TECHNOLOGY, VIDYANAGAR, KOTA',
  'Nirmala College of Pharmacy',
  'Oil Technological & Pharmaceutical Research Institute, JNTU, ANANTAPUR',
  'Parvatha Reddy Babul Reddy Visvodaya Institute of Technology & Science',
  'Pbr Vits',
  'PRABATH INST. OF PHARMACY, KURNOOL',
  'PRABHATH INSTITUTE OF BUSINESS MANAGEMENT, PARNAPALLI (V), NANDYAL',
  'PRABHATH INSTITUTE OF COMPUTER SCIENCES, PARNAPALLI (V), NANDYAL',
  'Prabhat Institute of Pharmacy, Kurnool',
  'P.Rami Reddy Memorial College of Pharmacy',
  'Priyadarshini College of Engineering (G1) Sullurpet',
  'Priyadarshini College of Engineering Technology',
  'Priyadarshini Institute of Technology Maharapuram, Tirupathi',
  'PRIYADARSHINI INST. OF TECH., RAMACHANDRAPURAM, TIRUPATI',
  'PVKK INSTITUTE OF TECHNOLOGY, ALAMURU, ANANTAPUR',
  'PVKK Institute of Technology, Anantapur',
  'QUBA COLLEGE OF ENGINEERING AND TECHNOLOGY, VENKATACHALAM, NELLORE',
  'Quba College of Engineering & Technology',
  'RAGHAVENDRA INSTITUTE OF MANAGEMENT SCIENCES',
  'Raghavendra Institute of Pharmaceutical Education & Research, Anantapur',
  'Rajeev Gandhi Memorial College of Engineering & Technology, Nandyal',
  'Rami Reddy Subbarami Reddy Engineering College, Kavali',
  "Rao's College of Pharmacy,",
  'Ratnam Institute of Pharmacy, Pidathapolur',
  'Ravindra College of Engineering for Women, kurnool',
  'Saastra College of Pharmaceutical Educational & Research, Guduru.',
  'Saastra College of Pharmaceutical Education and Research, NELLORE',
  'Safa College of Pharmacy, Kurnool',
  'Sai Rajeswari Institute of Technology',
  'SAI RAJESWARI INSTITUTE OF TECHNOLOGY, PRODDATUR',
  'Sanskriti School of Business, Putzaparthi',
  'Sanskriti School Of Engineering, Puttaparthi',
  'SANSKRITHI SCHOOL OF ENGINEERING, PUTTAPARTHI',
  'SANTHIRAM COLLEGE OF PHARMACY, KURNOOL',
  'Santhiram College of Pharmacy, Nandyal',
  'Santhiram Engineering College, Nandyal',
  'SANTHIRAM ENGINEERING COLLEGE, NANDYAL',
  'Seshachala College of Pharmacy, PUTTUR',
  'Seshachala College of Pharmacy, Tirupati Puttur',
  'Seven Hills College of Pharmacy, Tirupati',
  'SEVEN HILLS COLLEGE OF PHARMACY, TIRUPATHI',
  'Sharada Post-Graduate Institute of Research & Technological Sciences',
  'Shree Institute of Technical Education',
  'Shree Institute of Technical Education, Krishnapuram(V), Tirupathi (Rural)',
  'Shri Sai Institute of Engineering and Technology, Vadiyampet, Anantapur',
  'Shri Shirdi Sai Institute of Science and Engineering(9A), Vadiyampet, Anantapur',
  'Shri Shirdi Sai Institute of Science and Engineering, VADIYAMPETA, ANANTAPUR',
  'Siddhartha Educational Academy Group of Institutions, C.GOLLAPALLI, TIRUPATI',
  'Siddhartha Educational Academy Group of Institutions (Integrated Campus) Tirupathi',
  'SIDDARTHA INSTITUTE OF SCIENCE AND TECHNOLOGY',
  'Siddharth Institute of Engineering & Technology, Puttur',
  'Sir CV Raman Institute of Technology and Sciences, TADEPATRI, ANANTAPUR',
  'Sir C.V. Raman Institute of Technology & Sciences, Tadipatri,',
  'SKR College of Engineering & Technology, Manubolu',
  'Sreenivasa Inst. of Technology & Management Studies, Thimmasamudram, Chittoor',
  'Sree Rama Educational Society Group of Institutions',
  'Sree Rama Educational Society Group Of Institutions, TIRUPATI',
  'Sree Rama Engineering College, Tirupati',
  'Sree Rama Engineering College, TIRUPATI',
  'Sree Venkateswara Coe, Nellore',
  'SREE VENKATESWARA COLLEGE OF ENGINEERING',
  'Sree Vidyanikethan College Of Pharmacy, A.RANGAMPET',
  'Sree Vidyanikethan College Of Pharmacy, CHITTOOR',
  'Sree Vidyanikethan Engineering College, Tirupathi,',
  'Sri Annamacharya Institute of Technology & Science',
  'SRI BALAJI PG COLLEGE (MBA), ALAMURU (P), RUDRAMPETA',
  'SRI BALAJI PG COLLEGE (MCA), ALAMURU (P), RUDRAMPETA',
  'Sri Datta Sai College of MCA',
  'Sri Datta Sai School Of Business',
  'SRI DATTA SAI SCHOOL OF BUSINESS, PRAKSASAMPALLI (V), KOPPARTHI (P)',
  'Sri Kalahasteeswara Institute of Technology, SRIKALAHASTI',
  'Sri Krishna Chaitanya College Of Pharmacy, Madanapalli',
  'Sri Krishna Chaitanya College Of Pharmacy, MADANAPALLE',
  'Sri Lakshmi Narashima College of Pharmacy, Chittoor',
  'Sri Lakshmi Narasimha College of Pharmacy, PALLURU',
  'Sri Lakshmi Venkateswara Institute of Pharmaceutical Sciences, PRODDATUR',
  'Sri Lakshmi Venkateswar Institute of Pharmaceutical Sciences, Proddatur',
  'Srinivasa Institute of Technology & Sciences',
  'SRINIVASA INSTITUTE OF MANAGEMENT',
  'Srinivasa Institute of Pharmaceutical Sciences, PRODDATUR',
  'Srinivasa Institute of Pharmaceutical Sciences, Proddatur',
  'Srinivasa Institute of Technology & Sciences, UKKAYAPALLI, KADAPA',
  'SRINIVASA RAMANUJAN INSTITUTE OF TECHNOLOGY',
  'Sri Padmavathi School of Pharmacy, Tirupathi',
  'Sri Padmavathi School of Pharmacy, TIRUCHANOOR',
  'Sri Raghavendra Institute of Science & Technology, Kavali',
  'Sri Sai College of IT & Management',
  'Sri Sai Institute of Technology And Science, RAYACHOTI',
  'Sri Sai Inst. of Technology & Science, 2/714-18, Rayachoti',
  'Sri Venkatesa Perumal College of Engineering & Technology, Puttur',
  'SRI VENKATESWARA COLLEGE OF ENGINEERING',
  'Sri Venkateswara College of Engineering, KADAPA',
  'Sri Venkateswara College of Engineering, Karakambadi Road, Tirupathi',
  'Sri Venkateswara College of Pharmacy, Chittoor',
  'Sri Venkateswara Engineering College For Women, CHENNAIGUNTA, TIRUPATI',
  'Sri Venkateswara Engineering College, Karakambadi Road, Tirupathi',
  'Sri Venkateswara Institute of Technology & Sciences',
  'Sri Venkateswara Institute of Science and Technology, Kadapa',
  'Sri Venkateswara Institute of Technology, Hampapuram, Anantapur',
  'Sri Venkateswara Institute of Technology, HAMPAPURAM, ANANTAPUR',
  'Sri Venkateswara School of Business',
  'Sri Venkateswar College of Engineering & Technology, RVS Murukambattu, Chittoor',
  'Sri Vidyaniketan College of Pharmacy, Sri Sainath Nagar, A. Rangampet Tirupathi',
  'SSK INSTITUTE OF BUSINESS MANAGEMENT, VONTIMITTA (V & M)',
  'St. Johns COLLEGE OF ENGINEERING AND TECHNOLOGY, YERRAKOTA',
  'St. Johns College of Engineering & Technology, Yemmiganur',
  'St. Johns College of Pharmaceutical Sciences, KURNOOL',
  'St. Johns College of Pharmaceutical Sciences, Yemmiganur',
  'St. Mark Educational Institution Society Group of Institution, Rachunapalli, ANANTAPUR',
  'Sumourya Institute of Management',
  'Sun Institute of Pharmaceutical Education and Research, KAKUPALLI, NELLORE',
  'Sun Institute of Pharmaceutical Education & Research',
  'SV College of Engineering, TIRUPATI',
  'SVR Engineering College, AYYALURU, NANDYAL',
  'SVR Engineering College, Nandyal',
  'Swathi College of Pharmacy',
  'Swathi College of Pharmacy, VENKATACHALAM, NELLORE',
  'Tadipatri Engg College, Veerapuram, TADIPATRI',
  'Tadipatri Engineering College, Tadipatri',
  'Vaagdevi Institute Of Tech. And Science',
  'Vaagdevi Institute of Technology & Science, Proddatur',
  'Vagdevi College of Pharmacy and Research centre, NELLORE',
  'Vagdevi College of Pharmacy & Research Centre',
  'Vasavi Institute of Management & Computer Sciences',
  'Vasavi Institute of Pharmaceutical Science',
  'Vasavi Institute of Pharmaceutical Sciences, SIDDAVATAM, KADAPA',
  'VEDA COLLEGE OF PHARMACY, ALLAGADDA, KNL',
  'Vemu Institute Of Technology',
  'Vemu Institute of Technology, Chittoor',
  'Vignanasudha Institute of Management & Technology, Chittoor',
  'Vikas Institute of Business Management',
  'VISM, MADANAPALLE',
  'Visvodaya Engineering College',
  'Visvodaya Engineering College, Kavali',
  'Viswam Engineering College',
  'Yogananda Institute of Technology and Scien, ELAMANDYAM, TIRUPATI',
  'Yogananda Institute of Technology & Science, (YITS) Tirupathi',
  'A1 Global Institute of Engineering & Technology, Markapur',
  'Abhinav Institute of Management & Technology',
  'A B R College of Engineering and Technology',
  'Adarsa College of Pharmacy, G.Kothapalli, Gokavaram',
  'ADARSA COLLEGE OF PHARMACY, GOKAVARAM(P)',
  'Adarsh College of Engineering, NH-214, Chebrolu',
  'Addanki Institute of Management & Science, Near Singara Konda, NRT Road, North Addanki',
  'ADITYA COLLEGE OF ENGINEERING & TECHNOLOGY',
  'Aditya College of Pharmacy',
  'Aditya Engineering College, Aditya Nagar, ADB Road, Surampalem',
  'ADITYA INSTITUTE OF PHARMACEUTICAL SCIENCE & RESEARCH',
  'ADITYA INSTITUTE OF TECHNOLOGY & MANAGEMENT, K.Kothuru, Tekkali, Srikakulam District',
  'Aditya Pharmacy College, Surampalem',
  'A.K.R.G. College of Engineering and Technology, Nallajerla',
  'AKRG College of Pharmacy, Nallajerla',
  'AKRG COLLEGE OF PHARMACY, NALLAJERLA',
  'Akula Gopayya College of Engineering & Technology, Nh-5, Y-Junction, Prathipadu, Tadepalligudem',
  'Akula Sree Ramulu College of Engineering, Beside NH-5, By pass road, Tetali, Tanuku',
  'Amalapuram Institute of Management Sciences & College of Engineering, NH-214 Road, Mummidivaram',
  'Amara Institute of Engineering & Technology, Satuluru Post, Nadendla',
  'A.M. Reddy Memorial College of Engineering and Technology, Vinukonda Road, Narasaraopet',
  'Amrita Sai Institute of Science & Technology, Amrita Sai Nagar, Paritala, Kanchikacherla',
  'Anakapalle Merchants Association Konathala Subrahmanyam And Immidisetty Kanakaraju (Ask) College Of Tech. And Management',
  'Anakapalle Merchants Association Konathala Subrahmanyam And Immidisetty Kanakaraju (Ask) College Of Technology And Management',
  'Anakapalle Merchants Association Konathala Subrahmanyam & Immidisetty Kanaka Raju College of Technology & Management',
  'Andhra Loyola Institute of Engineering And Technology',
  'Andhra Loyola Institute of Engineering & Technology, Polytechnic Post Office, Loyola Campus, Vijayawada',
  'A S N WOMENS ENGINEERING COLLEGE',
  "A.S.N. Women's Engineering College, Kamala Educational Society, Burripalem Road, Tenali",
  'Avanthi Institute of Engineering Technology, Cherukupally, Bhogapuram',
  'Avanthi Institute of Engineering & Technology, Tamaram Village, Makavarapalem mandal, Narsipatnam',
  'Avanthi Institute of Pharmaceutical Sciences, Bhogapuram',
  'AVANTHI INSTITUTE OF PHARMACEUTICAL SCIENCES, BHOGAPURAM (P)',
  'AVANTHI INST. OF ENGG AND TECH, BHOGAPURAM(M), VIZINAGARAM D',
  'AVANTHIS RESEARCH & TECH ACADEMY, BHOGAPURAM, VIZIANAGARAM',
  "Avanthi's Research & Technology Academy, Basavapalem, Bhogapuram",
  "AVANTHI'S ST.THERESSA INSTITUTE OF ENGINEERING & TECHNOLOGY, Garbham Road, Garividi Village, Garividi Mandal",
  'BABA INSTITUTE OF TECHNOLOGY AND SCIENCES',
  'Baba Institute of Technology & Science, P.M. Palem, Bakkannapalem Village, Madhurawada',
  'B A & K R College of Pharmacy, NH-5, Doddavarappadu, Ongole',
  'BA&KR COLLEGE OF PHARMACY, ONGOLE(P)',
  'BA&KR MCA&MBA College, NH-5, Doddavarappadu, Ongole',
  'BAPATLA COLLEGE OF PHARMACY, BAPATLA',
  'BAPATLA COLLEGE OF PHRAMACY, BAPATLA (P)',
  'Bellamkonda Institute of Technology & Science, Kambhalapadu, Podili',
  'BELLAM KONDA INSTITUTE OF TECHNOLOGY & SCIENCES, PODILI(P)',
  'Benaiah institute of technology & Science, Christ Vidya Nagar, Burugupudi',
  'BEST Institute of Professional Studies, K.N Road, Tadepalli Village, Tadepalligudem',
  'Bhimavaram Institute of Engineering & Technology, Swamy Gnananadha Ashram Road, Pennada, Bhimavaram',
  'Bonam Venkata Chalamiah Engineering College, Odalarevu, Allavaram Mandal',
  'Bonam Venkata Chalamiah Institute of Technology and Science, Batlapalem, Amalapuram',
  'Buchepalli Venkayamma Subbareddy Engineering College, Ongole-Kurnool Road, Chimakurthy',
  'BVC College of Engineering, Palacharla, Rajanagaram Mandal',
  'Chaitanya College of Pharmacy, Devarajugattu, Near Markapur Town',
  'CHAITANYA ENGG. COLLEGE, KOMMADI, VISAKHAPATNAM',
  'Chaitanya Engineering College, Chaitanya Valley, Kommadi, Madhurawada',
  'Chaitanya Engineering College, Near Prakruthi Ashramam, Bhimavaram',
  'Chaitanya Institute of Computer Sciences, Chaitanya Nagar, S.B.H.Colony, Kakinada',
  'Chaitanya Institute of Science & Technology, Madhavapatnam, Samalkot, near Kakinada',
  'Chalapathi Institute Of Technology',
  'Chalapathi Institute of Technology',
  'Chalapathi Institute of Technology, A.R.Nagar, Amaravathi Road, Mothadaka, Tadikonda',
  'Chebrolu Engineering College, Near Power Station, Chebrolu',
  'Chintalapudi Engineering College, Chintalapudi, Ponnur',
  'chirala college of PG studies',
  'Chirala Engineering College, Ramapuram, Beach Road, Chirala',
  'Coastal Institute of Technology & Management, Narapam, Veerabhadrapuram, Kothavalasa',
  'COASTAL INST OF TECH AND MANAGEMENT, KOTHAVALASA, VIZIANAGAR',
  'DADI Institute of Engineering & Technology, Nh-5, Gavarapalem, Anakapalle',
  'DADI INST. OF ENGG. & TECH., GAVARAPALEM, ANAKAPALLE',
  'Datta Madhusudana Sastry Sri Venkateswara Hindu College of Engineering',
  'D C R M PHARMACY COLLEGE',
  'D.C.R.M Pharmacy College, Gangavaram Road, Inkollu',
  'Devineni Venkata Ramana & Dr. Hima Sekhar MIC College of Technology, Kanchikacherla',
  'Dhanekula Institute of Engineering & Technology, Ganguru, Penamaluru Mandal',
  'D J R College of Engineering & Technology, DJR Nagar, N.H.5, Velpur, Via Gudavalli, Vijayawada',
  'DJR Institute of Engineering and Technology, Velpur, Via Gudavalli, Vijayawada',
  'D.N.R. College of Engineering & Technology, Balusumudi, Bhimavaram',
  'D.N.R. School of Business Management, Balusumudi, Bhimavaram',
  'Dr.PAUL RAJ ENGINEERING COLLEGE',
  'Dr. Samuel George Institute of Engineering & Technology, George Town, Darimadugu, Markapur',
  'ELURU COLLEGE OF ENGINEERING & TECHNOLOGY, Chintigunta, Apparaopalem, Duggirala, Pedavegi, Eluru',
  'EMMANUEL COLLEGE OF PHARMACY',
  'EMMANUEL COLLEGE OF PHARMACY',
  'Eswar College of Engineering, Kesanupalli, Narasaraopet',
  'Gandhiji Institute of Science and Technology(GIST), Near Kongara Mallaiah Gattu, Gatti Bhimavaram NH.9, Vatsavai, Jaggayyapet',
  'GAYATHRI VIDYA PARISHAD COLL OF ENGG FOR WOMEN, VISAKHAPATNAM',
  'Gayatri Group of Institutions, Aswaraopet Road, Jangareddy gudem',
  'Gayatri Institute of Engineering & Technology, Aswaraopet road, Jangareddygudem',
  'Gayatri Vidya Parishad College of Engineering (Autonomous)',
  'Gayatri Vidya Parishad College of Engineering for Women, Madhurawada',
  'Gdrmm Coll. Of Engg. And Technology',
  'GIET College of Engineering, NH-5, Chaitanya Knowledge City, Rajahmundry',
  'GIET Engineering College',
  'Global Institute of Business Management, Markapur',
  'Global Institute Of Management And Technology',
  'Global Institute of Management & Technology, Bommuluru, Hanuman Junction, Bapulapadu Mandal',
  'GMR Institute of Technology (GMRIT), GMR Nagar, Rajam, Srikakulam Dt.',
  'Godavari Institute of Engineering & Technology (GIET), NH-5, Chaitanya nagar, Veluguvanda Village, Rajanagaram, Rajahmundry',
  'GOKUL College of pharmacy, Piridi, Bobbili',
  'Gokul Group of Institutions, AP',
  'GOKUL GROUP OF INSTITUTIONS, VZM',
  'GOKUL INSTITUTE OF TECHNOLOGY AND SCIENCES, PIRIDI, BOBBILI, AP',
  'Gokul PG College for MBA & MCA, PIRIDI, BOBBILI, AP',
  'GOKUL PHARMACY COLLEGE',
  'GONNA INSTITUTE OF INFORMATION TECHNOLOGY AND SCIENCES',
  'Gonna Institute of Information Technology & Science, Gonnavanipalem, Aganampudi, G.V.M.C',
  'Gonna Institute of Technology and Management',
  'Green Royal Academy of Pharmaceutical Education & Sciences, Koyyalagudem Mandal, Ponguturu',
  'GUNTUR ENGINEERING COLLEGE, NH-5, YANAMADALA, PRATHIPADU',
  'Gurivindapalli Devarandam Mary Memorial College of Engineering & Technology for Women, Ramanapet Road, Nandigama',
  'G V R & S College of Engineering & Technology, Ganjineenipuram, Near Budampadu',
  'GVVR INSTITUTE OF TECHNOLOGY, Vempa Road, Tundurru, Bhimavaram',
  'Helapuri Institute of Technology & Science, Vegavaram, Denduluru Mandalam, Eluru',
  'HINDU COLLEGE TECHNO CAMPUS, Amaravathi Road',
  'Ideal Institute of Technology, Vidyut Nagar, Kakinada',
  'Indira Institute of Technology & Sciences, Darimadugu, Markapur Mandal',
  'Indo American Institutions, Technical Campus, Indo American Vally, Sankaram Village, Batlapudi, Anakapalle Mandal',
  'International School of Technology and Sciences for Women',
  'JNTU KAKINADA',
  'JNTU KAKINADA UNIVERSITY COLLEGE OF ENGINEERING, NARASARAOPET',
  'Jagaiah Institute of Technology and Sciences, College of Engineering, Kalagampudi, Near Palakol, Elamanchili Mandal',
  'Jagaiah Institute of Technology & Pharmacy Sciences',
  'KAKINADA INSTITUTE OF ENGINEERING & TECHNOLOGY',
  'Kakinada Institute of Engineering & Technology for Women, Yanam Road, Tallarevu, Korangi, Kakinada',
  'Kakinada Institute of Engineering & Technology, Kist, Korangi, Yanam Road, Kakinada',
  'Kakinada Institute of Technological Sciences, A.Agraharam, Ramachandrapuram',
  'Kakinada Institute of Technology & Science, Tirupathi Village, Divilli, Peddapuram',
  'Kallam Harinatha Reddy Institute of Technology, NH-5, Chowdavaram',
  'Kamala institute of Management Studies, Krishnapuram Village, Markapuram Mandal',
  'Kaushik College of Engineering, Gambhiram, Anandpuram Mandal',
  'KC Reddy PG College, Janamguntapalem',
  'KITS College of Pharmacy for Women',
  'KITS COLLEGE OF PHARMACY FOR WOMEN',
  'KKR&KSR Institute of Technology & Sciences, VINJANAMPADU Village',
  'Koringa College Of Pharmacy',
  'KORINGA COLLEGE OF PHARMACY',
  'Krishna chaitanya Institute of Technology & Sciences, Jawahar nagar, Markapur',
  'Krishnaveni Engineering College for Women, Kesanupalli, Narasaraopet',
  'Kshtriya College of Management, Devarajugattu',
  'Lakireddy Bali Reddy College of Engineering, L.B. Reddy Nagar, Mylavaram',
  'Lendi Institute of Engineering & Technology, Jonnada, Denkada mandal',
  'LENDI INST OF ENGG AND TECHNOLOGY JONNADA, DENKADA, VZNM',
  'Lenora College of Engineering, Rampachodavaram',
  'Lingayas Institute of Management & Technology, Madalavarigudem, Via Nunna, Gannavaram Mandal, Vijayawada',
  'Loyola Institute of Technology and Management, Loyola Nagar, Dhulipalla, Sattenapalli',
  'MAESTRO SCHOOL OF PLANNING AND ARCHITECTURE',
  'Maharaj Vijayaram Gajapathi Raj College of Engineering, Chintalavalasa, Vizianagaram',
  'MALINENI LAAKSHMAIAH WOMEN\'S ENGINEERING COLLEGE, PULLADIGUNTA, VATTICHERUKURU',
  'Malineni Lakshmaiah Engineering College, Kanumalla, Singarayakonda',
  'Malineni Lakshmaiah MBA College, Kanumalli',
  "MALINENI PERUMALLU EDUCATIONAL SOCIETY'S GROUP OF INSTITUTIONS (INTIGRATED CAMPUS) PULLADIGUNTA, VATTICHERUKURU",
  'Mandava Institute of Engineering and Technology',
  'Mentey Padmanabham College of Engineering And Technology, K.G.R.L.College Road, Dirusumarru, Bhimavaram',
  'Miracle Educational Society Group of Institutions, Miracle City, Bhogapuram Mandal',
  'Montessori Siva Sivani Institute of Science & Technology college of Pharmacy, Gurrajupalem, Mylavaram',
  'MOTHER THERESA EDUCATIONAL SOCIETY GROUP OF INSTITUTIONS, VISSANNAPET',
  'M R K COLLEGE OF ARCHITECTURE',
  'MRR COLLEGE OF PHARMACY, NANDIGAMA(P)',
  'M.R.R. College of Pharmacy, Near DSP Office, Madhira Road, Nandigama',
  'Muttansetty Venkata Narayana Institute of Management Studies & Research, Vegavaram',
  'MVR College of Engineering & Technology, Beside Hanuman Statue on NH-9, Paritala, Vijayawada Rural',
  'Nadimpalli Satyanarayana Raju Institute of Technology, SONYAM, ANANDAPURAM, VIZAG',
  'Nirmala Institute of Pharmaceutical Sciences',
  'Nirmala Institute of Technology',
  'Nirmala Institute of Management Studies',
  'Nirmala Institute of P.G. Studies',
  'Nimra Institute of Science and Technology',
  'Nimra College of Business Management',
  'Nimra College of Engineering and Technology',
  'Nimra College of Pharmacy',
  'Nimra College of P.G. Studies',
  'Nimra Institute of Engineering and Technology',
  'Nova College of Business Management',
  'Nova College of Engineering and Technology',
  'Nova College of Pharmaceutical Education & Research',
  'NOVA COLLEGE OF PHARMACEUTICAL EDUCATION & RESEARCH, IBRAHIMPATNAM',
  'NOVA COLLEGE OF PHARMACY, JANGAREDDYGUDEM',
  'Nova College of Pharmacy',
  'NOVA INSTITUTE OF TECHNOLOGY, ELURU',
  'NOVA P.G. COLLEGE (MBA), ELURU',
  'NOVA P.G. COLLEGE (MCA), ELURU',
  "Nova's Institute of Technology",
  "Nova's College of Pharmacy",
  'NRI COLLEGE OF PHARMACY, POTHAVARAPPADU',
  'NRI Institute of Technology, Pothavarappadu, Agiripalli, Vijayawada Rural',
  'NRI Institute of Technology, Korangi, Agiripalli',
  'PACE Institute of Technology & Sciences, Vallur, Ongole',
  'Paladugu Parvathi Devi College of Engineering and Technology, Surampalli, Gannavaram',
  'P.N.C. & V.J.R. INSTITUTE OF ENGINEERING & TECHNOLOGY, PHIRANGIPURAM',
  'P.N.C. & V.J.R. Institute of Engineering & Technology',
  'POTTI SRIRAMULU CHALAVADI MALLIKARJUNA RAO COLLEGE OF ENGINEERING AND TECHNOLOGY, Vijayawada',
  'Pragati Engineering College',
  'Pragati Institute of Technology and Management',
  'Prakasam Engineering College',
  'PRASAD V. POTLURI SIDDHARTHA INSTITUTE OF TECHNOLOGY, Kanuru, Vijayawada',
  'Prasidha College of Engineering & Technology',
  'PRIYADARSHINI INSTITUTE OF TECHNOLOGY & MANAGEMENT',
  'PRIYADARSHINI INSTITUTE OF TECHNOLOGY & SCIENCE (CHINTALAPUDI)',
  'PRIYADARSHINI INSTITUTE OF TECHNOLOGY & SCIENCES FOR WOMEN, CHINTALAPUDI',
  'PYDAH COLLEGE OF ENGG. & TECH., GAMBHEERAM, ANANDAPURAM',
  'Pydah College of Engineering & Technology',
  'Pydah College of Engineering',
  'Qis College of Engineering & Technology, Vengamukkapalem, Ongole',
  'QIS COLLEGE OF PHARMACY, ONGOLE',
  'Qis College of Pharmacy, Ongole',
  'Raghu Engineering College, Dakamarri, Bheemunipatnam',
  'Raghu Institute of Technology, Dakamarri, Bheemunipatnam',
  'Rajamahendri Institute of Engineering & Technology',
  'Rao & Naidu Institute of Management & Science',
  'Ramachandra College of Engineering',
  'Ramachandra College of Pharmacy',
  'Rao & Naidu Engineering College',
  'R.N.R. (Rao & Naidu) Group of Institutions',
  'R.V.R. & J.C. College of Engineering',
  'R.K. College of Engineering',
  'SAI GANAPATHI ENGINEERING COLLEGE, Gidijala, Anandapuram',
  'SAI TIRUMALA NALABOTHU VENKATA RAO ENGINEERING COLLEGE',
  'SANKAR REDDY INSTITUTE OF PHARMACEUTICAL SCIENCES, BESTAVARIPETA',
  'SANKETIKA INSTITUTE OF TECHNOLOGY & MANAGEMENT, P.M. Palem, Visakhapatnam',
  'Sarada Institute of Science, Technology and Management (SISTAM)',
  'SARADA INSTITUTE OF TECHNOLOGY & MANAGEMENT',
  'Sasi Institute of Technology and Engineering (SITE)',
  'SASSING INSTITUTE OF TECHNOLOGY',
  'Sasi Institute of Technology & Engineering',
  'Satya Institute of Management Studies',
  'SATYA INSTITUTE OF TECHNOLOGY AND MANAGEMENT, Gajularega, Vizianagaram',
  'SEETHARAM COLLEGE OF PHARMACY, PATAVARAM',
  'Shri Vishnu Engineering College for Women',
  'SIDDHARTHA INSTITUTE OF PHARMACY, GATTEPALLI',
  'Simhadri Educational Society Group of Institutions',
  'Sir C.R.R. College of Engineering',
  'Sree Rama Institute of Technology & Science',
  'Sri Chaitanya Engineering College',
  'Sri Mittapalli College of Engineering',
  'Sri Mittapalli Institute of Technology for Women',
  'SRI PADMAVATHI INSTITUTE OF PHARMACEUTICAL SCIENCES, TIRUPATI',
  'Sri Sai Madhavi Institute of Science & Technology',
  'Sri Sarathi Institute of Engineering & Technology',
  'SRI VASAVI INSTITUTE OF ENGINEERING & TECHNOLOGY, PEDANA',
  'Sri Vasavi Engineering College, Pedana',
  'SRI VASAVI INSTITUTE OF PHARMACY, PEDANA',
  'Sri Vasavi Institute of Pharmaceutical Sciences, Pedana',
  'Sri Venkateswara College of Engineering, Etcherla, Srikakulam',
  'SRI VENKATESWARA COLLEGE OF PHARMACY, ETCHERLA',
  'Sri Venkateswara College of Pharmacy, Etcherla',
  'Sri Venkateswara Institute of Science & Information Technology (SVITS)',
  "St. Ann's College of Engineering & Technology",
  "ST. ANN'S COLLEGE OF PHARMACY, CHIRALA",
  "St. Ann's College of Pharmacy",
  "St. Mary's Group of Institutions Guntur",
  "St. Mary's Women's Engineering College",
  'SWARNANDHRA COLLEGE OF ENGINEERING & TECHNOLOGY, SEETHARAMPURAM',
  'Swarnandhra College of Engineering & Technology',
  'Swarnandhra Institute of Engineering & Technology',
  'Tirumala Engineering College',
  'UNIVERSITY COLLEGE OF ENGINEERING (JNTUK), KAKINADA',
  'UNIVERSITY COLLEGE OF ENGINEERING (JNTUK), VIZIANAGARAM',
  'University College of Engineering, Vizianagaram',
  "Vignan's Institute of Information Technology, Duvvada, Visakhapatnam",
  "Vignan's Institute of Engineering for Women",
  "Vignan's LARA Institute of Technology & Science, Vadlamudi, Chebrolu",
  "Vignan's Nirula Institute of Technology & Science for Women, Guntur",
  'VIGNAN INSTITUTE OF PHARMACEUTICAL TECHNOLOGY, GAJUWAKA',
  'Vignan Institute of Pharmaceutical Technology, Gajuwaka',
  'Vikas College of Engineering & Technology',
  'Vikas College of Pharmacy',
  'VIKAS INSTITUTE OF PHARMACEUTICAL SCIENCES, RAJAHMUNDRY',
  'Vikas Institute of Pharmaceutical Sciences, Rajahmundry',
  'Visakha Institute of Engineering & Technology, Narava, Visakhapatnam',
  'Visakha Institute of Management Studies',
  'VISAKHA INST. OF ENGG. AND TECH. NARAVA, VISAKHAPATNAM',
  'Vishwa Bharathi College of Pharmaceutical Sciences',
  'VISHWA BHARATHI COLLEGE OF PHARMACY, PERECHERLA',
  'Viswanadha Institute of Technology and Management, Mindivanipalem, Anandapuram',
  'Viswanadha Institute of Pharmaceutical Sciences',
  'V.S.M. College of Engineering',
  'WEST GODAVARI INSTITUTE OF SCIENCE AND TECHNOLOGY',
  'Other / Not listed',
].sort((a, b) => {
  if (a === 'Other / Not listed') return 1
  if (b === 'Other / Not listed') return -1
  return a.localeCompare(b)
})
