/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LocalRouteRouteImport } from "./routes/local/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as LocalIndexRouteImport } from "./routes/local/index";
import { Route as BuilderResumeIdRouteRouteImport } from "./routes/builder/$resumeId/route";
import { Route as BuilderResumeIdIndexRouteImport } from "./routes/builder/$resumeId/index";

const LocalRouteRoute = LocalRouteRouteImport.update({
  id: "/local",
  path: "/local",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const LocalIndexRoute = LocalIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LocalRouteRoute,
} as any);
const BuilderResumeIdRouteRoute = BuilderResumeIdRouteRouteImport.update({
  id: "/builder/$resumeId",
  path: "/builder/$resumeId",
  getParentRoute: () => rootRouteImport,
} as any);
const BuilderResumeIdIndexRoute = BuilderResumeIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => BuilderResumeIdRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/local": typeof LocalRouteRouteWithChildren;
  "/builder/$resumeId": typeof BuilderResumeIdRouteRouteWithChildren;
  "/local/": typeof LocalIndexRoute;
  "/builder/$resumeId/": typeof BuilderResumeIdIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/local": typeof LocalIndexRoute;
  "/builder/$resumeId": typeof BuilderResumeIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/local": typeof LocalRouteRouteWithChildren;
  "/builder/$resumeId": typeof BuilderResumeIdRouteRouteWithChildren;
  "/local/": typeof LocalIndexRoute;
  "/builder/$resumeId/": typeof BuilderResumeIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/local"
    | "/builder/$resumeId"
    | "/local/"
    | "/builder/$resumeId/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/local" | "/builder/$resumeId";
  id:
    | "__root__"
    | "/"
    | "/local"
    | "/builder/$resumeId"
    | "/local/"
    | "/builder/$resumeId/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LocalRouteRoute: typeof LocalRouteRouteWithChildren;
  BuilderResumeIdRouteRoute: typeof BuilderResumeIdRouteRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/local": {
      id: "/local";
      path: "/local";
      fullPath: "/local";
      preLoaderRoute: typeof LocalRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/local/": {
      id: "/local/";
      path: "/";
      fullPath: "/local/";
      preLoaderRoute: typeof LocalIndexRouteImport;
      parentRoute: typeof LocalRouteRoute;
    };
    "/builder/$resumeId": {
      id: "/builder/$resumeId";
      path: "/builder/$resumeId";
      fullPath: "/builder/$resumeId";
      preLoaderRoute: typeof BuilderResumeIdRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/builder/$resumeId/": {
      id: "/builder/$resumeId/";
      path: "/";
      fullPath: "/builder/$resumeId/";
      preLoaderRoute: typeof BuilderResumeIdIndexRouteImport;
      parentRoute: typeof BuilderResumeIdRouteRoute;
    };
  }
}

interface LocalRouteRouteChildren {
  LocalIndexRoute: typeof LocalIndexRoute;
}

const LocalRouteRouteChildren: LocalRouteRouteChildren = {
  LocalIndexRoute: LocalIndexRoute,
};

const LocalRouteRouteWithChildren = LocalRouteRoute._addFileChildren(
  LocalRouteRouteChildren,
);

interface BuilderResumeIdRouteRouteChildren {
  BuilderResumeIdIndexRoute: typeof BuilderResumeIdIndexRoute;
}

const BuilderResumeIdRouteRouteChildren: BuilderResumeIdRouteRouteChildren = {
  BuilderResumeIdIndexRoute: BuilderResumeIdIndexRoute,
};

const BuilderResumeIdRouteRouteWithChildren =
  BuilderResumeIdRouteRoute._addFileChildren(BuilderResumeIdRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocalRouteRoute: LocalRouteRouteWithChildren,
  BuilderResumeIdRouteRoute: BuilderResumeIdRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
