import {
  ArrowsClockwise,
  ArrowRight,
  Bell,
  BellSlash,
  BookOpen,
  BookmarkSimple,
  Brain,
  Briefcase,
  Buildings,
  Calendar,
  CaretDown,
  ChartLine,
  ChatCircle,
  Check,
  CheckCircle,
  ClipboardText,
  Clock,
  Compass,
  Copy,
  Crown,
  CurrencyDollar,
  DeviceMobile,
  Envelope,
  Export,
  Eye,
  EyeSlash,
  FileText,
  Fire,
  Folder,
  Gear,
  Globe,
  GraduationCap,
  Handshake,
  Heart,
  Leaf,
  Lightbulb,
  LinkSimple,
  Lock,
  LockOpen,
  MagnifyingGlass,
  MapPin,
  Microphone,
  Moon,
  Palette,
  PaperPlaneTilt,
  PencilLine,
  Plant,
  PuzzlePiece,
  Robot,
  Rocket,
  Shield,
  SignOut,
  Sparkle,
  Star,
  Sun,
  Tag,
  Target,
  Timer,
  Trash,
  TrendUp,
  Trophy,
  Tray,
  User,
  Warning,
  Wrench,
  X,
  XCircle,
  Lightning,
  Diamond,
  Phone,
  Package,
  CreditCard,
  Storefront,
  Book,
  Download,
  Users,
  SlidersHorizontal,
  List,
  Camera,
  Code,
  UserCircle,
  Scroll,
  Info,
  Hourglass,
  Upload,
  HeartStraight,
  EnvelopeSimple,
  PhoneCall,
  IdentificationCard,
  PencilSimple,
  FadersHorizontal,
  ForkKnife,
  Prohibit,
  TextAa,
  DownloadSimple,
  MapTrifold,
} from '@phosphor-icons/react'
import { cn } from '@/components/ui'

/** @type {Record<string, import('@phosphor-icons/react').Icon>} */
export const APP_ICONS = {
  dashboard: ChartLine,
  resume: FileText,
  jobs: Briefcase,
  applications: ClipboardText,
  salary: CurrencyDollar,
  interview: BookOpen,
  ai: Compass,
  'cover-letters': Envelope,
  linkedin: LinkSimple,
  'grammar-check': PencilLine,
  paraphrase: ArrowsClockwise,
  shield: Shield,
  user: User,
  bell: Bell,
  'bell-slash': BellSlash,
  settings: Gear,
  menu: List,
  sun: Sun,
  moon: Moon,
  logout: SignOut,
  sparkle: Sparkle,
  crown: Crown,
  trophy: Trophy,
  target: Target,
  fire: Fire,
  robot: Robot,
  star: Star,
  lock: Lock,
  'lock-open': LockOpen,
  plant: Plant,
  rocket: Rocket,
  lightning: Lightning,
  gem: Diamond,
  lightbulb: Lightbulb,
  handshake: Handshake,
  globe: Globe,
  chart: ChartLine,
  graduation: GraduationCap,
  brain: Brain,
  laptop: Briefcase,
  search: MagnifyingGlass,
  mobile: DeviceMobile,
  timer: Timer,
  wrench: Wrench,
  microphone: Microphone,
  puzzle: PuzzlePiece,
  calendar: Calendar,
  leaf: Leaf,
  palette: Palette,
  check: Check,
  'check-circle': CheckCircle,
  warning: Warning,
  x: X,
  'x-circle': XCircle,
  'arrow-right': ArrowRight,
  trash: Trash,
  copy: Copy,
  bookmark: BookmarkSimple,
  heart: Heart,
  clock: Clock,
  'map-pin': MapPin,
  buildings: Buildings,
  send: PaperPlaneTilt,
  eye: Eye,
  'eye-slash': EyeSlash,
  chat: ChatCircle,
  export: Export,
  'trend-up': TrendUp,
  tag: Tag,
  folder: Folder,
  inbox: Tray,
  'caret-down': CaretDown,
  pencil: PencilLine,
  envelope: Envelope,
  link: LinkSimple,
  note: PencilLine,
  offer: Trophy,
  rejected: XCircle,
  review: Eye,
  applied: PaperPlaneTilt,
  phone: Phone,
  package: Package,
  'credit-card': CreditCard,
  storefront: Storefront,
  book: Book,
  download: Download,
  users: Users,
  refresh: ArrowsClockwise,
  sliders: SlidersHorizontal,
  camera: Camera,
  map: MapTrifold,
  code: Code,
  'user-circle': UserCircle,
  scroll: Scroll,
  info: Info,
  hourglass: Hourglass,
  upload: Upload,
  'heart-outline': HeartStraight,
  'envelope-open': EnvelopeSimple,
  'phone-call': PhoneCall,
  'id-card': IdentificationCard,
  'pencil-simple': PencilSimple,
  faders: FadersHorizontal,
  food: ForkKnife,
  mute: Prohibit,
  'send-message': PaperPlaneTilt,
  'text-aa': TextAa,
  'download-simple': DownloadSimple,
  story: Book,
}

/** Legacy emoji → icon name (Firestore / old configs). */
const EMOJI_TO_NAME = {
  '📊': 'dashboard',
  '📄': 'resume',
  '💼': 'jobs',
  '📋': 'applications',
  '💰': 'salary',
  '📚': 'interview',
  '🧭': 'ai',
  '✉️': 'cover-letters',
  '🔗': 'linkedin',
  '✍️': 'grammar-check',
  '🔁': 'paraphrase',
  '🛡️': 'shield',
  '👤': 'user',
  '🔔': 'bell',
  '🔕': 'bell-slash',
  '⚙️': 'settings',
  '☀️': 'sun',
  '🌙': 'moon',
  '🚪': 'logout',
  '✨': 'sparkle',
  '👑': 'crown',
  '🏆': 'trophy',
  '🎯': 'target',
  '🔥': 'fire',
  '🤖': 'robot',
  '⭐': 'star',
  '🌟': 'star',
  '🔒': 'lock',
  '🔐': 'lock',
  '🌱': 'plant',
  '🚀': 'rocket',
  '⚡': 'lightning',
  '💎': 'gem',
  '💡': 'lightbulb',
  '🤝': 'handshake',
  '🌐': 'globe',
  '🎓': 'graduation',
  '🧠': 'brain',
  '💻': 'laptop',
  '🔍': 'search',
  '📱': 'mobile',
  '⏱️': 'timer',
  '🛠️': 'wrench',
  '🎤': 'microphone',
  '🧩': 'puzzle',
  '📅': 'calendar',
  '🌿': 'leaf',
  '🎨': 'palette',
  '✅': 'check-circle',
  '⚠️': 'warning',
  '✕': 'x',
  '❌': 'x-circle',
  '📑': 'copy',
  '🔖': 'bookmark',
  '❤️': 'heart',
  '🕒': 'clock',
  '📍': 'map-pin',
  '🏢': 'buildings',
  '📤': 'send',
  '👁': 'eye',
  '🙈': 'eye-slash',
  '💬': 'chat',
  '📝': 'pencil',
  '📧': 'envelope',
  '📭': 'inbox',
  '🎙️': 'microphone',
  '🎉': 'trophy',
  '👀': 'review',
  '📁': 'folder',
  '🏷️': 'tag',
  '📈': 'trend-up',
  '▾': 'caret-down',
  '○': 'check-circle',
  '🪪': 'id-card',
  '📜': 'scroll',
  '📷': 'camera',
  '⏳': 'hourglass',
  '👥': 'users',
  '📥': 'download',
  '✎': 'pencil-simple',
  '🎚️': 'faders',
  '🤐': 'mute',
  '📦': 'package',
  '🤍': 'heart-outline',
  '🍔': 'food',
  '📨': 'send-message',
  '🔄': 'refresh',
  '🗺️': 'map',
  '📖': 'story',
  '🔤': 'text-aa',
  '⤓': 'download-simple',
  '➤': 'send',
  '🗑️': 'trash',
  '👨‍💻': 'code',
  '👩‍💻': 'code',
}

export function resolveIconName(name) {
  if (!name) return 'bell'
  if (APP_ICONS[name]) return name
  if (EMOJI_TO_NAME[name]) return EMOJI_TO_NAME[name]
  return null
}

export default function AppIcon({
  name,
  className,
  weight = 'regular',
  size,
  ...props
}) {
  const resolved = resolveIconName(name)
  const Icon = resolved ? APP_ICONS[resolved] : Bell
  const sizeClass = size ? undefined : 'size-4'

  return (
    <Icon
      className={cn('shrink-0', sizeClass, className)}
      weight={weight}
      size={size}
      aria-hidden
      {...props}
    />
  )
}

export function AppIconOrNull({ name, ...props }) {
  if (!name && !resolveIconName(name)) return null
  return <AppIcon name={name} {...props} />
}
